project_id = "idhwokthhdbvdemnydlj"

[functions.analyze-stock]
verify_jwt = false

[functions.process-strategy]
verify_jwt = false

[functions.predict-chart]
verify_jwt = false

[functions.generate-blog]
verify_jwt = false
